# fly.toml app configuration file generated for alistpan on 2024-07-30T23:32:53+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'alistpan'
primary_region = 'ams'
kill_signal = 'SIGINT'
kill_timeout = '5s'
processes = []

[experimental]
  auto_rollback = true

[build]

[env]

[[mounts]]
  destination = "/opt/alist/data"
  source = "data"
  auto_extend_size_threshold = 0

[[services]]
  http_checks = []
  internal_port = 5244
  min_machines_running = 0
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  # [services.concurrency]
  #   hard_limit = 25
  #   soft_limit = 20
  #   type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 8080

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 5443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"


[[vm]]
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
