name: Fly Deploy cd
on:
  repository_dispatch:
  workflow_dispatch:
  push:
    branches:
      - main
  # schedule:
    # - cron: '0 8 3 * *'
  watch:
    types: [started]

jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Deploy

        uses: superfly/flyctl-actions/setup-flyctl@master
         # run: flyctl deploy --remote-only
        run: |
          sh ./deploy.sh
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          APP_NAME: ${{ secrets.APP_NAME }}
            # SQLUSER: ${{ secrets.SQLUSER }}
          DATABASE: ${{ secrets.DATABASE }}
            # SQLPASSWORD: ${{ secrets.SQLPASSWORD }}
            # SQLHOST: ${{ secrets.SQLHOST }}
            # SQLPORT: ${{ secrets.SQLPORT }}
            # SQLNAME: ${{ secrets.SQLNAME }}